## Data description
Faulty steel plates

https://www.kaggle.com/uciml/faulty-steel-plates/data

Content

There are 34 fields. The first 27 fields describe some kind of steel plate faults seen in images. Unfortunately, there is no other information that I know of to describe these columns.

    X_Minimum
    X_Maximum
    Y_Minimum
    Y_Maximum
    Pixels_Areas
    X_Perimeter
    Y_Perimeter
    Sum_of_Luminosity
    Minimum_of_Luminosity
    Maximum_of_Luminosity
    Length_of_Conveyer
    TypeOfSteel_A300
    TypeOfSteel_A400
    Steel_Plate_Thickness
    Edges_Index
    Empty_Index
    Square_Index
    Outside_X_Index
    Edges_X_Index
    Edges_Y_Index
    Outside_Global_Index
    LogOfAreas
    Log_X_Index
    Log_Y_Index
    Orientation_Index
    Luminosity_Index
    SigmoidOfAreas

The last seven columns are one hot encoded classes, i.e. if the plate fault is classified as "Stains" there will be a 1 in that column and 0's in the other columns.

    Pastry
    Z_Scratch
    K_Scatch
    Stains
    Dirtiness
    Bumps
    Other_Faults


In [181]:
import sklearn as sk
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import math

from sklearn.model_selection import cross_val_score, KFold, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn import metrics
from scipy.stats import sem

print('numpy version:', np.__version__)
print('pandas version:', pd.__version__)
print('scikit-learn version:', sk.__version__)
print('matplotlib version:', matplotlib.__version__)

%matplotlib inline

numpy version: 1.12.1
pandas version: 0.20.1
scikit-learn version: 0.18.1
matplotlib version: 2.0.2


In [182]:
datafolder = 'data/'
filename = 'faults.csv'
df = pd.read_csv(datafolder + filename, sep=',', low_memory=False, encoding = 'ISO-8859-1')
print(df.shape)
df.head()

(1941, 34)


X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0         42         50     270900     270944           267           17   
1        645        651    2538079    2538108           108           10   
2        829        835    1553913    1553931            71            8   
3        853        860     369370     369415           176           13   
4       1289       1306     498078     498335          2409           60   

   Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
0           44              24220                     76   
1           30              11397                     84   
2           19               7972                     99   
3           45              18996                     99   
4          260             246930                     37   

   Maximum_of_Luminosity      ...       Orientation_Index  Luminosity_Index  \
0                    108      ...                  0.8182           -0.2913   
1                    123      ...                  0.7931           -0.1756   
2                    125      ...                  0.6667           -0.1228   
3                    126      ...                  0.8444           -0.1568   
4                    126      ...                  0.9338           -0.1992   

   SigmoidOfAreas  Pastry  Z_Scratch  K_Scatch  Stains  Dirtiness  Bumps  \
0          0.5822       1          0         0       0          0      0   
1          0.2984       1          0         0       0          0      0   
2          0.2150       1          0         0       0          0      0   
3          0.5212       1          0         0       0          0      0   
4          1.0000       1          0         0       0          0      0   

   Other_Faults  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 34 columns]

In [183]:
y_pd = df[['Pastry', 'Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults']]

y = []

for index, row in y_pd.iterrows():
    y.append(row.argmax())
    
y = pd.Series(y)
    
df['Label'] = y.map({'Pastry': 0, 'Z_Scratch': 1, 'K_Scatch':2, 'Stains': 3, 'Dirtiness': 4, 'Bumps': 5, 'Other_Faults': 6})

df.head()

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0         42         50     270900     270944           267           17   
1        645        651    2538079    2538108           108           10   
2        829        835    1553913    1553931            71            8   
3        853        860     369370     369415           176           13   
4       1289       1306     498078     498335          2409           60   

   Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
0           44              24220                     76   
1           30              11397                     84   
2           19               7972                     99   
3           45              18996                     99   
4          260             246930                     37   

   Maximum_of_Luminosity  ...    Luminosity_Index  SigmoidOfAreas  Pastry  \
0                    108  ...             -0.2913          0.5822       1   
1                    123  ...             -0.1756          0.2984       1   
2                    125  ...             -0.1228          0.2150       1   
3                    126  ...             -0.1568          0.5212       1   
4                    126  ...             -0.1992          1.0000       1   

   Z_Scratch  K_Scatch  Stains  Dirtiness  Bumps  Other_Faults  Label  
0          0         0       0          0      0             0      0  
1          0         0       0          0      0             0      0  
2          0         0       0          0      0             0      0  
3          0         0       0          0      0             0      0  
4          0         0       0          0      0             0      0  

[5 rows x 35 columns]

In [184]:
X = df.loc[:, 'X_Minimum':'SigmoidOfAreas']

y = df['Label']

X


X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0            42         50     270900     270944           267           17   
1           645        651    2538079    2538108           108           10   
2           829        835    1553913    1553931            71            8   
3           853        860     369370     369415           176           13   
4          1289       1306     498078     498335          2409           60   
5           430        441     100250     100337           630           20   
6           413        446     138468     138883          9052          230   
7           190        200     210936     210956           132           11   
8           330        343     429227     429253           264           15   
9            74         90     779144     779308          1506           46   
10          106        118     813452     813500           442           13   
11          505        515     106604     106668           284           42   
12           46         58     179258     179312           480           15   
13          581        590     230644     230704           433           22   
14          451        466     368143     368208           728           30   
15          669        684     491552     491684          1097           59   
16          156        192     713788     714056          5044          167   
17           90        104     751059     751132           552           38   
18           82         89     844704     844729           137            8   
19         1601       1613      21349      21376           209           15   
20           17         28      42683      42717           284           18   
21           43         52      86284      86313           153           13   
22           63         72     115485     115504           106           10   
23           82         92     149044     149083           264           15   
24           75         84     184350     184383           201           17   
25         1363       1372    2128884    2128907           171            9   
26         1358       1372    2356396    2356435           395           19   
27         1404       1410    5202306    5202324            85            9   
28         1281       1302    4332564    4332815          3214           92   
29           49         62    4822354    4822392           386           15   
...         ...        ...        ...        ...           ...          ...   
1911        121        148     373848     373861           149           49   
1912        182        211     402237     402266           268           98   
1913        273        298     473262     473272            94           30   
1914        389        406     516427     516436            67           22   
1915        856        871     531684     531693            54           23   
1916        767        788     566837     566850            83           28   
1917        154        169     260124     260136            75           27   
1918        275        299    1133715    1133734           318           39   
1919        271        291    1488866    1488885           204           38   
1920        214        247    1538494    1538509           209           66   
1921        270        301    1563477    1563499           329           61   
1922         21         47    2867489    2867513           281           43   
1923         23         43    2985008    2985026           170           42   
1924         21         45    3063739    3063768           277           52   
1925         21         39    3411415    3411438           201           46   
1926       1053       1063     173208     173226            68           26   
1927        160        170     252936     252958            97           24   
1928       1303       1344      33298      33323           452           44   
1929        130        153     197701     197718        

In [185]:
# Standarize the features
scaler = StandardScaler().fit(X)
X = scaler.transform(X)

In [186]:
# Split the dataset into a training and a testing set; test set will be the 25% taken randomly
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=51)
print(X_train.shape, y_train.shape)


(1455, 27) (1455,)


In [192]:
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
clf = []

clf.append(("SVC linear", SVC(kernel='linear')))
clf.append(("SVC RBF", SVC(kernel='rbf')))
clf.append(("MLP 1 thick", MLPClassifier(hidden_layer_sizes=(27,), random_state=1)))
clf.append(("MLP 1 regular", MLPClassifier(hidden_layer_sizes=(13,), random_state=1)))
clf.append(("MLP 1 slim", MLPClassifier(hidden_layer_sizes=(5,), random_state=1)))
clf.append(("MLP 2 regular", MLPClassifier(hidden_layer_sizes=(18,9), random_state=1)))
clf.append(("MLP 2 thick", MLPClassifier(hidden_layer_sizes=(27,25), random_state=1)))
clf.append(("MLP 2 slim", MLPClassifier(hidden_layer_sizes=(10,5), random_state=1)))
clf.append(("MLP 3 regular", MLPClassifier(hidden_layer_sizes=(27, 15, 7), random_state=1)))
clf.append(("MLP 3 thick", MLPClassifier(hidden_layer_sizes=(27,26,25), random_state=1)))
clf.append(("MLP 3 slim", MLPClassifier(hidden_layer_sizes=(10, 7, 3), random_state=1)))

for c in clf:
    # Fit (= train) the classifier
    c[1].fit(X_train, y_train)



In [193]:
for c in clf:
    y_pred = c[1].predict(X_test)
    s = metrics.accuracy_score(y_test, y_pred)
    print(c[0])
    print(s)
    print()

SVC linear
0.732510288066

SVC RBF
0.748971193416

MLP 1 thick
0.742798353909

MLP 1 regular
0.732510288066

MLP 1 slim
0.621399176955

MLP 2 regular
0.742798353909

MLP 2 thick
0.748971193416

MLP 2 slim
0.670781893004

MLP 3 regular
0.740740740741

MLP 3 thick
0.736625514403

MLP 3 slim
0.699588477366



In [194]:
def evaluate_cross_validation(clf, X, y, K):
    # Create a k-fold cross validation iterator
    kf = KFold(K, shuffle=True, random_state=0)
    
    # By default the score used is the one returned by score method of the estimator (accuracy)
    scores = cross_val_score(clf, X, y, cv=kf)
    
    # scores = cross_val_score(clf, X, y, cv=K)     # This also works directly, without KFold function!
    
    print(scores)
    print("Mean score: {0:.3f} (+/-{1:.3f})".format(
        np.mean(scores), sem(scores)))
    
for c in clf:    
    print(c[0])
    evaluate_cross_validation(c[1], X_train, y_train, 5)
    print()

SVC linear
[ 0.6975945   0.71134021  0.68728522  0.72164948  0.72164948]
Mean score: 0.708 (+/-0.007)

SVC RBF
[ 0.74226804  0.74914089  0.72164948  0.72508591  0.7628866 ]
Mean score: 0.740 (+/-0.008)

MLP 1 thick
[ 0.74914089  0.74914089  0.73539519  0.71821306  0.73539519]
Mean score: 0.737 (+/-0.006)

MLP 1 regular
[ 0.70790378  0.74226804  0.70790378  0.73539519  0.72852234]
Mean score: 0.724 (+/-0.007)

MLP 1 slim
[ 0.63230241  0.604811    0.62199313  0.56013746  0.62199313]
Mean score: 0.608 (+/-0.013)

MLP 2 regular
[ 0.73883162  0.73883162  0.73195876  0.70790378  0.74226804]
Mean score: 0.732 (+/-0.006)

MLP 2 thick
[ 0.78694158  0.7628866   0.73539519  0.72852234  0.73195876]
Mean score: 0.749 (+/-0.011)

MLP 2 slim
[ 0.63573883  0.64261168  0.69415808  0.68728522  0.65292096]
Mean score: 0.663 (+/-0.012)

MLP 3 regular
[ 0.72164948  0.74226804  0.72852234  0.70790378  0.73539519]
Mean score: 0.727 (+/-0.006)

MLP 3 thick
[ 0.73195876  0.72852234  0.75257732  0.74914089  0.7

In [ ]:
ensemble = VotingClassifier(clf, weights=[1,1.7,1.5,1.4,1,1,2,1,1,1,1])

evaluate_cross_validation(ensemble, X_train, y_train, 5)